# Generated by Django 4.1.2 on 2023-10-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.ImageField(default='auctions/images/default.png', upload_to='auctions/images'),
        ),
    ]
