# Generated by Django 4.1.2 on 2023-10-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.ImageField(default='default.png', upload_to='auctions/images'),
        ),
    ]
