# Generated by Django 4.1.2 on 2023-10-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Auction',
            new_name='auction',
        ),
    ]
