# Generated by Django 4.1.2 on 2023-10-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_auction_comment_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
